---
- hosts: clients:replicas
  tasks:
    - name: "Pull docker image"
      shell: docker pull raytar/hotstuff:latest
    - name: "Create data volume"
      shell: docker volume create "{{inventory_hostname}}_hotstuff-data"
    - name: "Create tmp dir for data"
      tempfile:
        state: directory
        suffix: hotstuff
      register: tempdir
    - name: "Upload main config"
      copy:
        src: "{{ config_path }}/hotstuff.toml"
        dest: "{{tempdir.path}}/"
    - name: "Upload public keys"
      copy:
        src: "{{item}}"
        dest: "{{tempdir.path}}/"
        mode: 0644
      with_fileglob:
        - "{{config_path}}/*.key.pub"
    - name: "Upload TLS certificates"
      copy:
        src: "{{item}}"
        dest: "{{tempdir.path}}/"
        mode: 0644
      with_fileglob:
        - "{{config_path}}/*.crt"

- hosts: replicas
  vars:
    replica_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  tasks:
    - name: "Upload private key"
      copy:
        src: "{{config_path}}/{{replica_id}}.key"
        dest: "{{tempdir.path}}/"
        mode: 0600
    - name: "Upload self config"
      copy:
        src: "{{config_path}}/hotstuff_{{replica_id}}.toml"
        dest: "{{tempdir.path}}/self_config.toml"
        mode: 0644

- hosts: clients:replicas
  tasks:
    - name: "Copy into volume"
      shell: |
        docker container create --name {{inventory_hostname}}_hotstuff-temp -v {{inventory_hostname}}_hotstuff-data:/data hello-world
        docker cp {{tempdir.path}}/. {{inventory_hostname}}_hotstuff-temp:/data
        docker rm {{inventory_hostname}}_hotstuff-temp
    - name: "Remove temp dir"
      file:
        state: absent
        path: "{{tempdir.path}}"
