---
- hosts: replicas
  vars:
    replica_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  tasks:
    - name: Upload hotstuffserver binary
      copy:
        src: ../cmd/hotstuffserver/hotstuffserver
        dest: $HOME/hotstuffserver
        mode: 0755
    - name: Upload config file
      copy:
        src: "{{ config_path }}/hotstuff_{{ replica_id }}.toml"
        dest: $HOME/self_config.toml
        mode: 0644
    - name: Upload private key
      copy:
        src: "{{ config_path }}/{{ replica_id }}.key"
        dest: $HOME
        mode: 0644

- hosts: clients
  tasks:
    - name: Upload hotstuffclient binary
      copy:
        src: ../cmd/hotstuffclient/hotstuffclient
        dest: $HOME/hotstuffclient
        mode: 0755
    - name: Upload run_clients script
      copy:
        src: ./run_multiple_clients.sh
        dest: $HOME/run_clients.sh
        mode: 0755

- hosts: clients:replicas
  tasks:
    - name: Upload hotstuff.toml
      copy:
        src: "{{ config_path }}/hotstuff.toml"
        dest: $HOME/hotstuff.toml
        mode: 0644
    - name: Upload public keys
      copy:
        src: "{{ item }}"
        dest: $HOME
        mode: 0644
      with_fileglob:
        - "{{ config_path }}/*.key.pub"
