---
- hosts: clients
  gather_facts: no
  vars:
    num_clients: 1
    rate: 10000
    time: 60
    payload: 0
    maxinflight: 2500
    client_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  tasks:
    - name: Clean results dir
      file:
        path: /tmp/results
        state: absent
    - name: Create results dir
      file:
        path: /tmp/results
        state: directory
    - name: Start clients
      shell: ./run_clients.sh "{{ num_clients }}" "{{ inventory_hostname }}" "{{ client_id }}" "{{ rate }}" "{{ payload }}" "{{ maxinflight }}" "{{ time }}" 
      async: 1000
      poll: 0
      register: hotstuff_clients

- hosts: replicas
  gather_facts: no
  vars:
    batch_size: 100
    view_change: 100
  tasks:
    - name: Start servers
      shell: >
        ./hotstuffserver
        --config "$HOME/self_config.toml"
        --batch-size {{ batch_size }}
        --view-change {{ view_change }}

      async: 1000
      poll: 0

- hosts: clients
  gather_facts: no
  tasks:
    - name: Wait for clients to exit
      async_status:
        jid: "{{ hotstuff_clients.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30

- hosts: replicas
  gather_facts: no
  tasks:
    - name: Kill servers
      shell: killall -s INT hotstuffserver
      ignore_errors: yes

- hosts: clients
  gather_facts: no
  tasks:
    - name: Fetch data
      synchronize:
        src: "/tmp/results/"
        dest: "{{ destdir }}"
        mode: pull
